### PR TITLE
Improved constant values generated code (2) (issue #84)

### LINKED ISSUE #84: Improved constant values generated code (2)
Hi @illicitonion and @danielhenrymantilla,

I discovered this crate yesterday and it's seems perfect for me. Thank you !
I am using the last version `0.5.7`.
I ran `cargo expand` on my code to better understand what it is doing.

The result was quite "ugly" (shown bellow).
I looked in the past issues and found #12 that enhances exactly that.
I tested at the `0.4.2` version and indeed the expansion was "pretty".

Then I tried to find at which version the expansion got "ugly" again.
It happended at the `0.5.0` version.

I am looking at the code right now to see how to fix that.
I never wrote macro so it's a bit cryptic to me....

The "ugly" expansion:
```rust
impl ::num_enum::TryFromPrimitive for EncodingFormat {
        type Primitive = u8;
        const NAME: &'static str = "EncodingFormat";
        fn try_from_primitive(
            number: Self::Primitive,
        ) -> ::core::result::Result<Self, ::num_enum::TryFromPrimitiveError<Self>> {
            #![allow(non_upper_case_globals)]
            const Postcard__num_enum_0__: u8 = 2;
            const Json__num_enum_0__: u8 = u8::wrapping_add(2, 1);
            const MessagePack__num_enum_0__: u8 = u8::wrapping_add(
                u8::wrapping_add(2, 1),
                1,
            );
            const Pickle__num_enum_0__: u8 = u8::wrapping_add(
                u8::wrapping_add(u8::wrapping_add(2, 1), 1),
                1,
            );
            const BSON__num_enum_0__: u8 = u8::wrapping_add(
                u8::wrapping_add(u8::wrapping_add(u8::wrapping_add(2, 1), 1), 1),
                1,
            );
            const CBOR__num_enum_0__: u8 = u8::wrapping_add(
                u8::wrapping_add(
                    u8::wrapping_add(u8::wrapping_add(u8::wrapping_add(2, 1), 1), 1),
                    1,
                ),
                1,
            );
            const CSV__num_enum_0__: u8 = u8::wrapping_add(
                u8::wrapping_add(
                    u8::wrapping_add(
                        u8::wrapping_add(u8::wrapping_add(u8::wrapping_add(2, 1), 1), 1),
                        1,
                    ),
                    1,
                ),
                1,
            );
            const Bencode__num_enum_0__: u8 = u8::wrapping_add(
                u8::wrapping_add(
                    u8::wrapping_add(
                        u8::wrapping_add(
                            u8::wrapping_add(
                                u8::wrapping_add(u8::wrapping_add(2, 1), 1),
                                1,
                            ),
                            1,
                        ),
                        1,
                    ),
                    1,
                ),
                1,
            );
            #[deny(unreachable_patterns)]
            match number {
                Postcard__num_enum_0__ => ::core::result::Result::Ok(Self::Postcard),
...
```

The "pretty" expansion:
```rust
impl ::num_enum::TryFromPrimitive for EncodingFormat {
        type Primitive = u8;
        const NAME: &'static str = "EncodingFormat";
        fn try_from_primitive(
            number: Self::Primitive,
        ) -> ::core::result::Result<Self, ::num_enum::TryFromPrimitiveError<Self>> {
            #![allow(non_upper_case_globals)]
            const Postcard: u8 = 2;
            const Json: u8 = u8::wrapping_add(Postcard, 1);
            const MessagePack: u8 = u8::wrapping_add(Json, 1);
            const Pickle: u8 = u8::wrapping_add(MessagePack, 1);
            const BSON: u8 = u8::wrapping_add(Pickle, 1);
            const CBOR: u8 = u8::wrapping_add(BSON, 1);
            const CSV: u8 = u8::wrapping_add(CBOR, 1);
            const Bencode: u8 = u8::wrapping_add(CSV, 1);
            match number {
                Postcard => ::core::result::Result::Ok(EncodingFormat::Postcard),
...
```

### PR DESCRIPTION
**Pull request by GilShoshan94**
Fixes #84

Please check this well.
It seems to work.

### CODE REVIEW

**Comment by illicitonion** [comment]
Thanks for the PR! I think the goal of fixing #84 is a good one, but CI is failing. It looks like you're expanding to roughly:
```rust
const One__num_enum_0__: u8 = u8::wrapping_add(Zero, 1);
```

but need to be expanding to:
```rust
const One__num_enum_0__: u8 = u8::wrapping_add(Zero__num_enum_0__, 1);
```

as per https://github.com/illicitonion/num_enum/blob/bc957b1a7ed59da8a9e71dbb0147118ff9052aeb/num_enum_derive/src/lib.rs#L219

I'd recommend extracting that `format_ident!("{}__num_enum_{}__", info.ident, index)` into a function, and calling it both from where it currently is and from where you're currently making `ident_clone`. (You'd want to use `0` as the index).

**Comment by GilShoshan94** [comment]
I didn't know how to revert the last commit and try again... 
I didn't see the `__num_enum_0__`...

Retrying

**Comment by GilShoshan94** [comment]
Ok I tried as you said, I made an helper function that takes the indent and the index and uses it where it was currently and where I made 'ident_clone', and I used `0` as index.

It works for the simple case.
But it won't work if we use Variant Alternative....

Here bellows an example of an expansion after applying what we talked about with Variant Alternative:

```rust
impl ::num_enum::TryFromPrimitive for EncodingFormat {
        type Primitive = u8;
        const NAME: &'static str = "EncodingFormat";
        fn try_from_primitive(
            number: Self::Primitive,
        ) -> ::core::result::Result<Self, ::num_enum::TryFromPrimitiveError<Self>> {
            #![allow(non_upper_case_globals)]
            const Postcard__num_enum_0__: u8 = 2;
            const Json__num_enum_0__: u8 = u8::wrapping_add(Postcard__num_enum_0__, 1);
            const MessagePack__num_enum_0__: u8 = u8::wrapping_add(
                Json__num_enum_0__,
                1,
            );
            const Pickle__num_enum_0__: u8 = u8::wrapping_add(
                MessagePack__num_enum_0__,
                1,
            );
            const Pickle__num_enum_1__: u8 = 6;
            const Pickle__num_enum_2__: u8 = 7;
            const BSON__num_enum_0__: u8 = u8::wrapping_add(Pickle__num_enum_0__, 1);
            const CBOR__num_enum_0__: u8 = u8::wrapping_add(BSON__num_enum_0__, 1);
            const CSV__num_enum_0__: u8 = u8::wrapping_add(CBOR__num_enum_0__, 1);
            const Bencode__num_enum_0__: u8 = u8::wrapping_add(CSV__num_enum_0__, 1);
            #[deny(unreachable_patterns)]
            match number {
                Postcard__num_enum_0__ => ::core::result::Result::Ok(Self::Postcard),
                Json__num_enum_0__ => ::core::result::Result::Ok(Self::Json),
                MessagePack__num_enum_0__ => {
                    ::core::result::Result::Ok(Self::MessagePack)
                }
                Pickle__num_enum_0__ | Pickle__num_enum_1__ | Pickle__num_enum_2__ => {
                    ::core::result::Result::Ok(Self::Pickle)
                }
                BSON__num_enum_0__ => ::core::result::Result::Ok(Self::BSON),
                CBOR__num_enum_0__ => ::core::result::Result::Ok(Self::CBOR),
                CSV__num_enum_0__ => ::core::result::Result::Ok(Self::CSV),
                Bencode__num_enum_0__ => ::core::result::Result::Ok(Self::Bencode),
                #[allow(unreachable_patterns)]
                _ => {
                    ::core::result::Result::Err(::num_enum::TryFromPrimitiveError {
                        number,
                    })
                }
            }
        }
    }
```

I need to know the last index...

Or, if we can somehow reverse the order of the alternative variant index in such a way that the index 0 is always the biggest value than it would work.

**Comment by GilShoshan94** [comment]
Ok, I did reverse the ordered the index with '.rev()' on the range and it fix the issue !.

```rust
impl ::num_enum::TryFromPrimitive for EncodingFormat {
        type Primitive = u8;
        const NAME: &'static str = "EncodingFormat";
        fn try_from_primitive(
            number: Self::Primitive,
        ) -> ::core::result::Result<Self, ::num_enum::TryFromPrimitiveError<Self>> {
            #![allow(non_upper_case_globals)]
            const Postcard__num_enum_0__: u8 = 2;
            const Json__num_enum_0__: u8 = u8::wrapping_add(Postcard__num_enum_0__, 1);
            const MessagePack__num_enum_0__: u8 = u8::wrapping_add(
                Json__num_enum_0__,
                1,
            );
            const Pickle__num_enum_2__: u8 = u8::wrapping_add(
                MessagePack__num_enum_0__,
                1,
            );
            const Pickle__num_enum_1__: u8 = 6;
            const Pickle__num_enum_0__: u8 = 7;
            const BSON__num_enum_0__: u8 = u8::wrapping_add(Pickle__num_enum_0__, 1);
            const CBOR__num_enum_0__: u8 = u8::wrapping_add(BSON__num_enum_0__, 1);
            const CSV__num_enum_0__: u8 = u8::wrapping_add(CBOR__num_enum_0__, 1);
            const Bencode__num_enum_0__: u8 = u8::wrapping_add(CSV__num_enum_0__, 1);
            #[deny(unreachable_patterns)]
            match number {
                Postcard__num_enum_0__ => ::core::result::Result::Ok(Self::Postcard),
                Json__num_enum_0__ => ::core::result::Result::Ok(Self::Json),
                MessagePack__num_enum_0__ => {
                    ::core::result::Result::Ok(Self::MessagePack)
                }
                Pickle__num_enum_0__ | Pickle__num_enum_1__ | Pickle__num_enum_2__ => {
                    ::core::result::Result::Ok(Self::Pickle)
                }
                BSON__num_enum_0__ => ::core::result::Result::Ok(Self::BSON),
                CBOR__num_enum_0__ => ::core::result::Result::Ok(Self::CBOR),
                CSV__num_enum_0__ => ::core::result::Result::Ok(Self::CSV),
                Bencode__num_enum_0__ => ::core::result::Result::Ok(Self::Bencode),
                #[allow(unreachable_patterns)]
                _ => {
                    ::core::result::Result::Err(::num_enum::TryFromPrimitiveError {
                        number,
                    })
                }
            }
        }
    }
```

But then I got thinking, what is change the order of the alternative variant in the attribute on the enum variant itself?

So instead of `#[num_enum(alternatives = [ 6, 7 ])]` I wrote `#[num_enum(alternatives = [ 9, 7 ])]`.

And here it fails...

I got this expansion:
```rust
impl ::num_enum::TryFromPrimitive for EncodingFormat {
        type Primitive = u8;
        const NAME: &'static str = "EncodingFormat";
        fn try_from_primitive(
            number: Self::Primitive,
        ) -> ::core::result::Result<Self, ::num_enum::TryFromPrimitiveError<Self>> {
            #![allow(non_upper_case_globals)]
            const Postcard__num_enum_0__: u8 = 2;
            const Json__num_enum_0__: u8 = u8::wrapping_add(Postcard__num_enum_0__, 1);
            const MessagePack__num_enum_0__: u8 = u8::wrapping_add(
                Json__num_enum_0__,
                1,
            );
            const Pickle__num_enum_2__: u8 = u8::wrapping_add(
                MessagePack__num_enum_0__,
                1,
            );
            const Pickle__num_enum_1__: u8 = 9;
            const Pickle__num_enum_0__: u8 = 7;
            const BSON__num_enum_0__: u8 = u8::wrapping_add(Pickle__num_enum_0__, 1);
            const CBOR__num_enum_0__: u8 = u8::wrapping_add(BSON__num_enum_0__, 1);
            const CSV__num_enum_0__: u8 = u8::wrapping_add(CBOR__num_enum_0__, 1);
            const Bencode__num_enum_0__: u8 = u8::wrapping_add(CSV__num_enum_0__, 1);
            #[deny(unreachable_patterns)]
            match number {
                Postcard__num_enum_0__ => ::core::result::Result::Ok(Self::Postcard),
                Json__num_enum_0__ => ::core::result::Result::Ok(Self::Json),
                MessagePack__num_enum_0__ => {
                    ::core::result::Result::Ok(Self::MessagePack)
                }
                Pickle__num_enum_2__ | Pickle__num_enum_1__ | Pickle__num_enum_0__ => {
                    ::core::result::Result::Ok(Self::Pickle)
                }
                BSON__num_enum_0__ => ::core::result::Result::Ok(Self::BSON),
                CBOR__num_enum_0__ => ::core::result::Result::Ok(Self::CBOR),
                CSV__num_enum_0__ => ::core::result::Result::Ok(Self::CSV),
                Bencode__num_enum_0__ => ::core::result::Result::Ok(Self::Bencode),
                #[allow(unreachable_patterns)]
                _ => {
                    ::core::result::Result::Err(::num_enum::TryFromPrimitiveError {
                        number,
                    })
                }
            }
        }
    }
```

I think that we need to sort the variant in order to avoid collision.

What do you think ? 

I guess there is a question on behevior definition on the Variant alternatives, if the following variant have to 1) be explicitly set or 2) if we want to increment from the biggest value  or 3) if we want to increment from the smallest value but skipping automatically on those taken...

For example:
```rust
#[derive(Copy, Clone, Debug, PartialEq, Eq, TryFromPrimitive)]
#[repr(u8)]
pub enum EncodingFormat {
    Postcard = 2,
    Json,
    MessagePack,
    #[num_enum(alternatives = [7,8,10])]
    Pickle,
    BSON,
    CBOR,
    CSV,
    Bencode,
}
```

So EncodingFormat::Json is 3, MessagePack = 4, Pickle is 5 | 7 | 8 | 10, and now for BSON ? if we pick the 3) way, it would be BSOM = 6, CBOR=9, CSV=11, and Bencode=12.

What's your take ?

**Pull request closed without merging**
