### PR TITLE
Derive with strings not quote

### LINKED ISSUE #13: Performance Issue on Large enums
```Rust
#[derive(TryFromPrimitive)]
```

takes about two minutes on my machine for an enum with ~6700 entries on every compile (even when the module it's in hasn't changed).

With `RUSTFLAGS="-Ztime"` set, the log output shows that the time is spent in the `expand crate` step.

### PR DESCRIPTION
**Pull request by illicitonion**
For large (thousands of variants) enums, this drops the time to generate
from minutes to seconds.

I don't love this, but it's a significant speedup, and the code we're
generating is pretty simple...

I'll file a bug against proc-quote about the perf.

Fixes #13 /cc @anlumo

### CODE REVIEW

**Comment by danielhenrymantilla** [comment]
Oh, that's both interesting and disappointing 😅 
Since the performance gain is huge, we'll have to settle for this version. I am still curious though: since you have already done some benchmarks, could you also benchmark using `::quote::quote!` rather than `::proc_quote::quote!` ? (_c.f._ #15)

**Comment by illicitonion** [comment]
I checked - `quote` took 88 seconds, compared to `proc-quote`'s `94`. I'm going to merge #14 (and switch to regular `quote`), then rebase and merge this on top, so that it will be easy for us to switch back if the perf issues get resolved :)

**Comment by dtolnay** [comment]
The slowness is a bug in the compiler's libproc_macro: https://github.com/rust-lang/rust/issues/65080.

I opened https://github.com/alexcrichton/proc-macro2/pull/199 with a workaround that drops the cargo expand time of https://github.com/illicitonion/num_enum_regression_13 (using `quote`) from 118 seconds to 2.0 seconds on my machine.

**Comment by danielhenrymantilla** [comment]
Wow, thanks for stepping in, @dtolnay. The change you have suggested to `proc-macro2` is great, it should be faster to get going than the original fix on `proc-macro`.

So the best course of action for this PR is to wait for a `quote` release (or git `rev`) to depend on this patched version of `proc-macro2`, right?

**Comment by dtolnay** [comment]
I published the workaround in proc-macro2 so the performance should already be fixed once you run `cargo update`.

**Comment by illicitonion** [comment]
Closing - fix is pushed to transitive dep :)

**Pull request closed without merging**
